# Ejercicios Modulo 5. Librerías especializadas en datos (Soluciones)

Consideraciones a tener en cuenta: 

* Guardar este documento con el siguiente formato para su entrega: __M5_05_nombre_apellido1_apellido2__
* Realizar los ejercicios con las herramientas vistas en las sesiones. 
* Comentar el código
* Utilizar nombres de variables apropiados, si vais a guardar una nota, llamar a esa variable nota, no n o x

**1) Trabajemos con NumPy**

* Importa numpy y usa un alias para poder utilizar sus recursos
* Crea un array de elementos (del 10 al 100)
* Invertir el array
* Crear un array 3x3 con valores de 0 a 8
* Crear un array identidad de 6x6
* Crear un array con valores al azar con forma 3x3x3
* Crear dos arrays con valores al azar A y B, verificar si son iguales (hay varias opciones, investigar)

In [12]:
import numpy as nm

arr100 = list(range(101))
del arr100[:10]

# El array del 10 al 100
miArray = nm.array(arr100)
print(miArray)

# Invertimos el array
arrayInvertido = miArray[::-1]
print(arrayInvertido)

# Creamos el array 3x3
m = nm.arange(0, 9)
final = nm.reshape(m, [3,3])
print(final)

# La matriz identidad de 6x6
identi = nm.identity(6)
print(identi)

# Matriz aleaotria
mRandom = nm.random.randint(100, size = (3, 3, 3))
print(mRandom)

a = nm.random.randint(100, size = (3, 3, 3))
b = nm.random.randint(100, size = (3, 3, 3))
print("Los arrays 'a' y 'b' son iguales --->", nm.array_equiv(a, b))

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[[66 92 51]
  [60  7 93]
  [57 88  7]]

 [[20  2 27]
  [15 71 87]
  [37 51 27]]

 [[21 72 22]
  [19 79

**2) Sigamos con NumPy**

* Crear un array de 100 elementos aleatorios comprendidos entre 1 y 1000 (pueden ser números enteros).
* Este array se llamara dólares
* Crear otro array llamado euros
* Realizar la conversión de los precios en dólares del primer array al segundo array en euros. Se puede serguir la siguiente conversión:
    - 1 EUR = 1,14362 USD
    - 1 USD = 0,874413 EUR
* Mostrar el resultado del array de euros pero redondeado a 2 decimales

In [19]:
dolares = nm.random.randint(1000, size = 100)
euros = nm.zeros(100)
print(euros)

conversionDolares = dolares * 0.874413
euros = conversionDolares + euros
print("\n", euros)

# Redondeo a dos decimales
eurosRound = nm.around(euros, decimals = 2)
print("\n", eurosRound)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]

 [364.630221 220.352076 744.999876 546.508125 819.324981  39.348585
 290.305116 135.534015 772.106679 847.306197 739.753398 870.040935
 235.217097 503.661888 340.146657 737.130159 344.518722 527.271039
 208.110294  37.599759  80.445996 246.584466  55.962432   2.623239
 655.80975  205.487055 457.317999  62.083323 610.340274 396.983502
 699.5304   614.712339 673.29801  605.968209 137.282841 617.335578
 247.458879 368.127873 440.704152 326.156049 795.71583  537.763995
  71.701866   5.246478 104.92956  380.369655 536.015169 121.543407
 236.09151  208.110294  83.069235 286.807464 335.774592 480.92715
 823.697046  41.097411 414.471762 416.220588 543.010473 729.260442
 671.549184 804.45996  

**3) Trabajemos con pandas**

* Importa pandas y usa un alias para poder utilizar sus recursos
* Cargar como dataframe de pandas el csv 05_05_imdb_titulos.csv y mostrar sus 5 primeros registros
* Cargar como dataframe de pandas el csv 05_05_imdb_elenco.csv y mostrar sus 5 primeros registros
* Mostrar el número de registros del dataframe de titulos
* Mostrar el número de registros del dataframe de elenco
* Mostrar las 5 peliculas más antiguas del listado de titulos
* Mostrar las peliculas que en el titulo tienen la palabra "Dracula". También mostrar el número total de peliculas que coincidan con este requisito
* Mostrar los 10 titulos más comunes (que más se repiten)
* Mostrar cual fue la primer pelicula hecha titulada "Romeo and Juliet" 
* Listar todas las peliculas que contengan la palabra "Exorcist" ordenadas de la más vieja a la más reciente
* Mostrar cuantas peliculas fueron hechas en el año 1950
* Mostrar cuantas peliculas fueron hechas de 1950 a 1959
* Mostrar todos los roles o papeles que hubo en la pelicula "The Godfather". También mostrar el número total de coincidencias
* Mostrar el elenco completo ordenado por la clasificacion "n" de la pelicula "Dracula" de 1958
* Mostrar cuantos papeles de "Bruce Wayne" han sido hechos en la historia de las peliculas
* Mostrar cuantos papeles ha hecho "Robert De Niro" en su carrera
* Listado de papeles como protagonista (n=1) que tuvo el actor "Charlton Heston" en la década de los 60's, ordenado por año de forma descendente
* Mostrar cuantos papeles para actores hubo en la década de los 50's
* Mostrar cuantos papeles para actrices hubo en la década de los 50's

In [1]:
import pandas as pd

In [73]:
# Caragamos los CSV y vemos sus 5 primeros registros
titulos = pd.read_csv("05_05_imdb_titulos.csv")
elenco = pd.read_csv("05_05_imdb_elenco.csv")
print(titulos.head())
print("\n", elenco.head())

# Numero de registros
print("\nEl numero de registros de TITULOS es de", len(titulos), 'registros')
print("\nEl numero de registros de ELENCO es de", len(elenco), 'registros')

# Las peliculas mas antiguas
titulosOrdenYear = titulos.sort_values('year', ascending = True)
print("Las cinco peliculas mas antiguas son las siguientes:\n", titulosOrdenYear.head())

# Las que tengan las palabra Dracula
condicion = titulos["title"].str.find("Dracula")
titulosDracula = titulos["title"][condicion != -1]
print("Las peliculas que contienen la palabra 'Dracula' son las siguientes:")
for i in titulosDracula:
    print("\t-->", i)
print("Un total de {} titulos".format(len(titulosDracula)))

# Mostrar 10 titulos mas repetitivos
rep10titulos = titulos["title"].value_counts().head(10)
print(rep10titulos)

#La pelicula primigenia de "Romeo y Julieta"
romJul = titulosOrdenYear.loc[titulosOrdenYear["title"] == "Romeo and Juliet", ["title", "year"]]
print(romJul.head(1))

# Ordenar las que contengan "Exorcist"
condicion = titulos["title"].str.find("Exorcist")
dtexorTiYear = titulos.loc[condicion != -1, ["title", "year"]]
exorOrdYear = dtexorTiYear.sort_values('year', ascending = True)
print(exorOrdYear)

# La cantidad de peliculas hechas en 1950
titulos1950 = titulos["title"][titulos["year"] == 1950]
print("El numero de peliculas hechas en '1950' es de {} peliculas".format(len(titulos1950)))

# Hechas entre 1950 y 1959
titulos5059 = titulos["title"][(titulos["year"] >= 1950) & (titulos["year"] <= 1959)]
print("El numero de peliculas hechas entre los años 50 y 59 es de {} peliculas".format(len(titulos5059)))


# Roles en "The Godfather"
rolesPadrin = elenco.loc[(elenco["title"] == "The Godfather"), ["character"]]
print("Los roles son los siguientes:")
for i in rolesPadrin["character"]:
    print("\t--->", i)
    
rolesDupli = rolesPadrin.value_counts()
contador = 0
for r in rolesDupli:
    if r > 1:
        contador += 1
print(contador, "coincidencias en los roles")


# Elenco ordenado por n 
dtDracula1958 = elenco.loc[(elenco["title"] == "Dracula") & (elenco["year"] == 1958), ["year", "title", "character", "n"]]
dtDracula1958.sort_values('n')

# Bruce Wayne a lo largo de la historia
numBW_historia = len(elenco["character"][elenco["character"] == "Bruce Wayne"])
print("Las apariciones en peliculas de 'Bruce Wayne' han sido", numBW_historia)

# Numeros de papeles en la carrera de Robert
numRob = len(elenco["name"][elenco["name"] == "Robert De Niro"])
print("El numero de papeles en la carrera de Robert de Niro es de", numRob)

# Papeles de protagonista de "Charlton Heston" en la decada de los 60´s
dfPapeleProtaChar = elenco.loc[(elenco["year"] >= 1960) & 
           (elenco["year"] <= 1969) & 
           (elenco["name"] == "Charlton Heston") & 
           (elenco["n"] == 1), 
           ["name", "year", "character", "n"]]
print(dfPapeleProtaChar.sort_values('year', ascending = False))

# Papeles actores 50´s
serPapelM50 = elenco["type"][(elenco["type"] == "actor") & 
                            (elenco["year"] >= 1950) & 
                            (elenco["year"] <= 1959)]
print("El numero de papeles para actores en las decada de los 50´s es de", len(serPapelM50))

# Papeles actrices 50´s
serPapelF50 = elenco["type"][(elenco["type"] == "actress") & 
                            (elenco["year"] >= 1950) & 
                            (elenco["year"] <= 1959)]
print("El numero de papeles para actrices en las decada de los 50´s es de", len(serPapelF50))

                                   title  year
0                                 Mahler  1974
1           Ogon, voda i... mednye truby  1968
2  Ana Nojoom bent alasherah wamotalagah  2014
3                      Malu de Bicicleta  2010
4             Nazareno Apostol: Boy Ahas  1989

                   title  year      name   type                character     n
0        Closet Monster  2015  Buffy #1  actor                  Buffy 4  31.0
1       Suuri illusioni  1985    Homo $  actor                   Guests  22.0
2   Battle of the Sexes  2017   $hutter  actor          Bobby Riggs Fan  10.0
3  Secret in Their Eyes  2015   $hutter  actor          2002 Dodger Fan   NaN
4            Steve Jobs  2015   $hutter  actor  1988 Opera House Patron   NaN

El numero de registros de TITULOS es de 230407 registros

El numero de registros de ELENCO es de 3564650 registros
Las cinco peliculas mas antiguas son las siguientes:
                                                     title  year
13229         